openapi: 3.1.0
info:
  title: Alchemorsel API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service status
  /api/v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/profile:
    get:
      summary: Get authenticated profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile with user recipes
    put:
      summary: Update profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Update success
  /api/v1/profile/logout:
    post:
      summary: Logout user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logged out
  /api/v1/recipes:
    get:
      summary: List recipes
      parameters:
        - name: q
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: dietary
          in: query
          schema:
            type: string
        - name: exclude
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Recipes
    post:
      summary: Create recipe
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '201':
          description: Created recipe
  /api/v1/recipes/{id}:
    get:
      summary: Get recipe by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recipe
    put:
      summary: Update recipe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete recipe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
  /api/v1/recipes/{id}/favorite:
    post:
      summary: Favorite recipe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Favorited
    delete:
      summary: Remove recipe from favorites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Unfavorited
  /api/v1/llm/query:
    post:
      summary: Generate recipe using LLM
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LLMQuery'
      responses:
        '201':
          description: Generated recipe
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        username:
          type: string
        dietary_preferences:
          type: array
          items:
            type: string
        allergies:
          type: array
          items:
            type: string
      required:
        - name
        - email
        - password
        - username
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
    Recipe:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        image_url:
          type: string
        ingredients:
          type: array
          items:
            type: string
        instructions:
          type: array
          items:
            type: string
        calories:
          type: number
        protein:
          type: number
        carbs:
          type: number
        fat:
          type: number
        user_id:
          type: string
      required:
        - name
    LLMQuery:
      type: object
      properties:
        query:
          type: string
        intent:
          type: string
        recipe_id:
          type: string
      required:
        - query
        - intent
