-- Add macro nutrition columns to recipes table
ALTER TABLE recipes
    ADD COLUMN IF NOT EXISTS calories INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS protein DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fat DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS carbs DOUBLE PRECISION DEFAULT 0;
