-- Add macronutrient columns to recipes
ALTER TABLE recipes
    ADD COLUMN IF NOT EXISTS calories DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS protein DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS carbs DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fat DOUBLE PRECISION DEFAULT 0;
