name: Backend CI
# To Trigger changes for CI
on:
  push:
    branches: [ codex-1 ]
  pull_request:
    branches: [ codex-1 ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Debug environment
        run: |
          echo "Checking PostgreSQL service:"
          docker ps
          echo "Testing connection:"
          PGPASSWORD=runner psql -h localhost -p 5432 -U runner -d test_db -c "\l" || echo "Connection failed"

      - name: Install pgvector extension
        run: |
          PGPASSWORD=runner psql -h localhost -p 5432 -U runner -d test_db -c "CREATE EXTENSION IF NOT EXISTS vector;"

      - name: Run tests
        run: go test ./... -v
        env:
          CI: "true"
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: runner
          DB_PASSWORD: runner
          DB_NAME: test_db
          DB_SSL_MODE: disable
          JWT_SECRET: test_secret
          LLM_API_KEY: test_key

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest 