name: Backend CI
# To Trigger changes for CI
on:
  push:
    branches: [ codex-1 ]
  pull_request:
    branches: [ codex-1 ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Print environment for debugging
        run: env | sort

      - name: Run tests
        run: go test -v -cover ./...
        env:
          CI: "true"
          # TestContainers config
          TESTCONTAINERS_RYUK_DISABLED: "true"
          TESTCONTAINERS_RYUK_CONTAINER_PRIVILEGED: "true"
          # Server config
          SERVER_HOST: localhost
          SERVER_PORT: 8080
          # Database config
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ vars.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ vars.TEST_DB_NAME }}
          DB_SSL_MODE: disable
          # Redis config
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          TEST_REDIS_PASSWORD: ${{ secrets.TEST_REDIS_PASSWORD }}
          REDIS_URL: redis://:${{ secrets.TEST_REDIS_PASSWORD }}@localhost:6379/0
          # Auth config
          TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
          # LLM config
          LLM_API_KEY: ${{ secrets.TEST_LLM_API_KEY }}

      - name: Clear golangci-lint cache
        run: |
          rm -rf ~/.cache/golangci-lint
          rm -rf ~/.cache/go-build
          rm -rf ~/go/pkg

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: latest
          args: --config=.golangci.yml
