name: CI Test

on:
  push:
    branches: [ codex-1 ]
  pull_request:
    branches: [ codex-1 ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "Checking PostgreSQL service:"
          docker ps
          echo "Environment variables:"
          echo "TEST_DB_USER: ${{ secrets.TEST_DB_USER }}"
          echo "TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}"
          echo "TEST_DB_PASSWORD exists: ${{ secrets.TEST_DB_PASSWORD != '' }}"
          echo "Testing connection:"
          PGPASSWORD=${{ secrets.TEST_DB_PASSWORD }} psql -h localhost -p 5432 -U ${{ secrets.TEST_DB_USER }} -d ${{ secrets.TEST_DB_NAME }} -c "\l" || echo "Connection failed" 
