name: CI Test

on:
  push:
    branches: [ codex-1 ]
  pull_request:
    branches: [ codex-1 ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "Checking PostgreSQL service:"
          docker ps
          echo "Testing connection with hardcoded values:"
          PGPASSWORD=runner psql -h localhost -p 5432 -U runner -d test_db -c "\l" || echo "Connection failed" 
